-- schema-step39-ccavai-category.sql
-- Persist the per-draft category badge (the UPPERCASE eyebrow rendered onto the
-- branded image, e.g. "TIP" / "SERVICE" / "NEWS"). It is generated by the CCAVAI
-- workflow in the tenant's content language, so storing it lets the dashboard
-- re-render the branded image (edit headline / replace subject) WITHOUT guessing
-- a label or defaulting to an English "AI NEWS" — which previously produced a
-- Spanish "SERVICIO" badge on English content (and vice-versa).
alter table public.ccavai_drafts
  add column if not exists category_label text;
