import { createClient } from "@/lib/supabase/server";

export type CcavaiDraft = {
  id: string;
  run_id: string;
  generated_at: string;
  platform: "linkedin" | "instagram" | "facebook" | "x";
  story_title: string;
  story_url: string | null;
  story_source: string | null;
  story_summary: string | null;
  /** UPPERCASE eyebrow badge baked onto the branded image, in the tenant's
   *  content language (e.g. "TIP" / "SERVICE" / "NEWS"). Generated by CCAVAI. */
  category_label: string | null;
  draft_title: string | null;
  draft_body: string;
  draft_hashtags: string[] | null;
  visual_prompt: string | null;
  image_prompt: string | null;
  image_url: string | null;
  subject_image_url: string | null;
  branded_headline: string | null;
  accent_phrases: string[] | null;
  status: "pending" | "approved" | "rejected" | "posted" | "archived";
  decided_at: string | null;
  decided_notes: string | null;
  posted_url: string | null;
};

export type CcavaiRun = {
  id: string;
  started_at: string;
  finished_at: string | null;
  status: string;
  drafts_created: number;
  stories_picked: number;
};

export type CcavaiStats = {
  drafts_generated: number;
  pending_review: number;
  approved: number;
  posted: number;
  rejected: number;
  last_run_at: string | null;
  window_start: string;
};

export type CcavaiSettings = {
  tenant_id: string;
  enabled: boolean;
  platforms: string[];
  tone: "professional_warm" | "casual_friendly" | "bold_punchy" | "educational" | "industry_voice";
  rss_sources: { url: string; name?: string }[];
  drafts_per_run: number;
  generate_images: boolean;
  image_style: "branded_modern" | "editorial" | "photographic" | "illustration";
  auto_post: boolean;
  brand_vocabulary: string | null;
  do_not_say: string[];
  updated_at: string;
};

export async function listCcavaiDrafts(
  tenantId: string,
  opts: { status?: CcavaiDraft["status"]; limit?: number } = {},
): Promise<CcavaiDraft[]> {
  const supabase = await createClient();
  let q = supabase
    .from("ccavai_drafts")
    .select(
      "id, run_id, generated_at, platform, story_title, story_url, story_source, story_summary, category_label, draft_title, draft_body, draft_hashtags, visual_prompt, image_prompt, branded_headline, accent_phrases, status, decided_at, decided_notes, posted_url",
    )
    .eq("tenant_id", tenantId)
    .order("generated_at", { ascending: false })
    .limit(opts.limit ?? 200);

  if (opts.status) q = q.eq("status", opts.status);

  const { data } = await q;
  return (data ?? []).map((row) => ({
    ...(row as Omit<CcavaiDraft, "image_url" | "subject_image_url">),
    image_url: `/api/ccavai/drafts/${(row as { id: string }).id}/image`,
    subject_image_url: `/api/ccavai/drafts/${(row as { id: string }).id}/image?variant=subject`,
  })) as CcavaiDraft[];
}

export async function listCcavaiRuns(tenantId: string, limit = 30): Promise<CcavaiRun[]> {
  const supabase = await createClient();
  const { data } = await supabase
    .from("ccavai_runs")
    .select("id, started_at, finished_at, status, drafts_created, stories_picked")
    .eq("tenant_id", tenantId)
    .order("started_at", { ascending: false })
    .limit(limit);
  return (data ?? []) as CcavaiRun[];
}

export async function getCcavaiSettings(tenantId: string): Promise<CcavaiSettings | null> {
  const supabase = await createClient();
  const { data } = await supabase
    .from("ccavai_settings")
    .select("*")
    .eq("tenant_id", tenantId)
    .maybeSingle();
  if (!data) return null;
  const row = data as unknown as Omit<CcavaiSettings, "rss_sources"> & {
    rss_sources: unknown;
  };
  return {
    ...row,
    rss_sources: Array.isArray(row.rss_sources)
      ? (row.rss_sources as { url: string; name?: string }[])
      : [],
  };
}

export async function getCcavaiStats(
  tenantId: string,
  window: "today" | "week" | "month" | "7d" | "30d" = "today",
): Promise<CcavaiStats | null> {
  const supabase = await createClient();
  // Tenant-scoped directly off ccavai_drafts/ccavai_runs. The old global
  // `ccavai_stats(p_window)` RPC was NOT tenant-scoped — it leaked every
  // tenant's counts to every tenant. Query the tables with an explicit
  // tenant_id filter (+ RLS) instead.
  const start = new Date();
  if (window === "month") {
    start.setUTCDate(1);
  } else if (window !== "today") {
    start.setUTCDate(start.getUTCDate() - (window === "30d" ? 30 : 7));
  }
  start.setUTCHours(0, 0, 0, 0);
  const startISO = start.toISOString();

  const [draftsRes, lastRunRes] = await Promise.all([
    supabase.from("ccavai_drafts").select("status").eq("tenant_id", tenantId).gte("generated_at", startISO),
    supabase
      .from("ccavai_runs")
      .select("started_at")
      .eq("tenant_id", tenantId)
      .order("started_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
  ]);

  const rows = (draftsRes.data ?? []) as { status: string }[];
  const countByStatus = (s: string) => rows.filter((r) => r.status === s).length;
  return {
    drafts_generated: rows.length,
    pending_review: countByStatus("pending"),
    approved: countByStatus("approved"),
    posted: countByStatus("posted"),
    rejected: countByStatus("rejected"),
    last_run_at: (lastRunRes.data as { started_at?: string } | null)?.started_at ?? null,
    window_start: startISO,
  };
}

export type ContentReadiness = {
  business_description: boolean;
  services_count: number;
  faq: boolean;
  brand_voice: boolean;
  /** 0-100 completeness used for the progress bar */
  score: number;
};

/**
 * How much per-tenant business context CCAVAI has to work with. The richer
 * this is, the more on-brand the business-pillar content. Drives the
 * "content readiness" nudge on the CCAVAI settings page.
 */
export async function getContentReadiness(
  tenantId: string,
): Promise<ContentReadiness> {
  const supabase = await createClient();
  const [tenantRes, servicesRes, settingsRes] = await Promise.all([
    supabase.from("tenants").select("voice_persona").eq("id", tenantId).maybeSingle(),
    supabase
      .from("services")
      .select("id", { count: "exact", head: true })
      .eq("tenant_id", tenantId)
      .eq("active", true),
    supabase
      .from("ccavai_settings")
      .select("brand_vocabulary")
      .eq("tenant_id", tenantId)
      .maybeSingle(),
  ]);

  const persona =
    ((tenantRes.data as { voice_persona?: Record<string, unknown> } | null)
      ?.voice_persona) ?? {};
  const businessDesc =
    typeof persona.business_description === "string" &&
    persona.business_description.trim().length > 20;
  const rebecca = (persona.rebecca ?? {}) as Record<string, unknown>;
  const faq =
    typeof rebecca.faq === "string" && rebecca.faq.trim().length > 20;
  const servicesCount = servicesRes.count ?? 0;
  const brandVoice =
    typeof (settingsRes.data as { brand_vocabulary?: string } | null)
      ?.brand_vocabulary === "string" &&
    ((settingsRes.data as { brand_vocabulary?: string }).brand_vocabulary ?? "")
      .trim().length > 0;

  // Weighted: description + services are the load-bearing inputs.
  let score = 0;
  if (businessDesc) score += 35;
  if (servicesCount > 0) score += 35;
  if (faq) score += 20;
  if (brandVoice) score += 10;

  return {
    business_description: businessDesc,
    services_count: servicesCount,
    faq,
    brand_voice: brandVoice,
    score,
  };
}
